name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main # or master before October 2020
  # schedule:
  #   - cron: "0 0 * * *"

env:
  PAGES_REPO_NWO: robert-bogan/myblog.git

jobs:
  github-pages:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}